{
    'name': 'Web PJMS Site',
    'version': '16.0.1.0.2',
    'summary': 'Sitio web PJMS — Tienda Online',
    'description': 'Sitio web PJMS con snippets reutilizables, menú dinámico y override visual de website_sale.',
    'category': 'Website',
    'license': 'LGPL-3',
    'author': 'Method',
    'depends': [
        'website',
        'website_sale',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ribbon_data.xml',
        'data/website_data.xml',
        'views/product_ribbon_views.xml',
        'views/layout/pj_layout.xml',
        'views/layout/pj_header.xml',
        'views/layout/pj_footer.xml',
        'views/snippets/s_pj_hero.xml',
        'views/snippets/s_pj_trust_bar.xml',
        'views/snippets/s_pj_featured.xml',
        'views/snippets/s_pj_categories.xml',
        'views/snippets/s_pj_promo_banner.xml',
        'views/snippets/s_pj_bestsellers.xml',
        'views/snippets/s_pj_brands.xml',
        'views/snippets/s_pj_newsletter.xml',
        'views/snippets/snippets.xml',
        'views/pages/home.xml',
        'views/pages/contacto.xml',
        'views/pages/contactus.xml',
        'views/pages/categoria.xml',
        'views/website_sale_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            ('prepend', 'web_pjms/static/src/scss/primary_variables.scss'),
            'web_pjms/static/src/scss/pj_tokens.scss',
            'web_pjms/static/src/scss/pj_layout.scss',
            'web_pjms/static/src/scss/pj_section_common.scss',
            'web_pjms/static/src/scss/snippets/s_pj_hero.scss',
            'web_pjms/static/src/scss/snippets/s_pj_trust_bar.scss',
            'web_pjms/static/src/scss/snippets/s_pj_featured.scss',
            'web_pjms/static/src/scss/snippets/s_pj_categories.scss',
            'web_pjms/static/src/scss/snippets/s_pj_promo_banner.scss',
            'web_pjms/static/src/scss/snippets/s_pj_bestsellers.scss',
            'web_pjms/static/src/scss/snippets/s_pj_brands.scss',
            'web_pjms/static/src/scss/snippets/s_pj_newsletter.scss',
            'web_pjms/static/src/scss/website_sale.scss',
            'web_pjms/static/src/js/snippets/s_pj_hero/000.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
}
